stages:
  - dependency_build
  - build

deploy:
  image: docker:19.03.12
  stage: dependency_build
  services:
    - name: docker:19.03.12-dind
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"

.build:
  image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
  stage: build
  services:
    - docker:dind
  variables:
      LUNCH: ""
  script:
    - mkdir -p /build/android/lineage; cd /build/android/lineage
    - repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
    - git clone --recurse-submodules -j8 https://gitlab.com/switchroot/android/manifest.git -b lineage-17.1-icosa_sr .repo/local_manifests || echo Manifest already present--snacking now.
    - .repo/local_manifests/snack/snack.sh -y
    - source build/envsetup.sh
    - lunch ${LUNCH}
    - mka bacon
    - OUTFOLDER=icosa-tab-$(date +'%Y%m%d')-dev
    - mkdir -p /build/artifacts/${OUTFOLDER}
    - cp out/target/product/icosa_sr/lineage-17.1-*-UNOFFICIAL-*.zip out/target/product/icosa_sr/boot.img out/target/product/icosa_sr/install/*.dtb /build/artifacts/${OUTFOLDER}/
  artifacts:
    paths:
      - /build/artifacts/${OUTFOLDER}/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'lineage-17.1-icosa_sr'"
      when: manual

icosa-build:
  extends: .build
  variables:
      LUNCH: "lineage_icosa_sr-userdebug"

