stages:
  - prepare
  - setup
  - icosa:tab
  - icosa:atv

#
# PREPARE STAGE
#
prepare:
  image: docker:dind
  stage: prepare
  services:
    - name: docker:dind
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"

#
# SETUP STAGE
#
setup:
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
  stage: setup
  needs: ["prepare"]
  services:
    - docker:dind
  variables:
    LINEAGE_BRANCH: "lineage-17.1"
    MANIFEST_BRANCH: "lineage-17.1-icosa_sr"
  script:
    - mkdir -p /build/android/lineage; cd /build/android/lineage
    - repo init -u https://github.com/LineageOS/android.git -b "${LINEAGE_BRANCH}"
    - git clone --recurse-submodules -j8 https://gitlab.com/switchroot/android/manifest.git -b "${MANIFEST_BRANCH}" .repo/local_manifests || echo Manifest already present--snacking now.
    - .repo/local_manifests/snack/snack.sh -y

#
# BUILD JOB TEMPLATE
#
.build:
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
  services:
    - docker:dind
  variables:
    BUILD_TYPE: ""
    TYPE: ""
  before_script:
    - rm out/target/product/${PRODUCT}/lineage-1*.1-*-UNOFFICIAL-*.zip || true
  script:
    - cd /build/android/lineage
    - source build/envsetup.sh
    - lunch "${BUILD_TYPE}"
    - make installclean
    - mka bacon
    - mkdir -p switchroot/android switchroot/install
    - cp out/target/product/${PRODUCT}/boot.img out/target/product/${PRODUCT}/install/*.dtb switchroot/install/
    - wget -O switchroot/install/twrp.img https://github.com/makinbacon21/switchroot-android-build/raw/master/external/twrp.img
    - cp out/target/product/${PRODUCT}/icosa.scr switchroot/android/boot.scr
    - cp out/target/product/${PRODUCT}/common.scr switchroot/android/
    - zip -j ${CI_PROJECT_DIR}/icosa-${TYPE}-$(date +'%Y%m%d')-dev.zip out/target/product/${PRODUCT}/lineage-1*.1-*-UNOFFICIAL-*.zip switchroot/android
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/icosa-${TYPE}-*-dev.zip
#
# ICOSA TAB
#
icosa-tab:
  extends: .build
  stage: icosa:tab
  needs: ["setup"]
  variables:
    BUILD_TYPE: "lineage_icosa_sr-userdebug"
    TYPE: "tab"
    PRODUCT: "icosa_sr"

#
# ICOSA TV
#
icosa-atv:
   extends: .build
   stage: icosa:atv
   needs: ["icosa-tab"]
   variables:
     BUILD_TYPE: "lineage_icosa_tv_sr-userdebug"
     TYPE: "atv"
     PRODUCT: "icosa_tv_sr"
